name: rubocop-todo-regenerator
author: ydah <t.yudai92@gmail.com>
description: Custom action to regenerate `.rubocop_todo.yml` and create Pull Request.
branding:
  color: red
  icon: git-pull-request
inputs:
  github_token:
    description: GitHub access token to run another workflows from new pull request.
    required: false
  triggered_label:
    description: Specify the label to be triggered.
    required: false
    default: "rubocop-todo-regenerate"
  preparation_command:
    description: Preparation commands to be plugged in after the repository is checked out and Ruby is set up.
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checking out repository
      if: github.event.label.name == inputs.triggered_label
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Ruby
      if: github.event.label.name == inputs.triggered_label
      uses: ruby/setup-ruby@v1
    - name: Run preparation command
      run: ${{ inputs.preparation_command }}
      if: github.event.label.name == inputs.triggered_label
      shell: bash
    - run: |
        gem update bundler
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        env bundle install
        bundle exec rubocop --regenerate-todo
        git add -u
        git commit -m "rubocop --regenerate-todo"
        git push
      if: github.event.label.name == inputs.triggered_label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
    - name: Post-processing
      uses: actions-ecosystem/action-remove-labels@v1
      if: github.event.label.name == inputs.triggered_label
      with:
        labels: ${{ inputs.triggered_label }}
