name: Linting
on:
  - pull_request
permissions:
  contents: write

jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v4
      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  mdformat:
    name: Mdformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mdformat
        uses: ydah/mdformat-action@main
        with:
          number: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
